### PR TITLE
Add blog post about DBAL 2.5.2 release

### PR DESCRIPTION
**Pull request by deeky666**

### CODE REVIEW

**Comment by zeroedin-bill** [comment]
OK

**Comment by Ocramius** [comment]
@deeky666 just one thing: the release notes at http://www.doctrine-project.org/jira/secure/ReleaseNote.jspa?projectId=10040&version=10731 report nothing. Maybe wanna check that?

**Comment by Ocramius** [comment]
Hmm, interesting, that's actually visible for logged in users only.

**Comment by zeroedin-bill** [comment]
@Ocramius maybe that's why you've been copying release notes from JIRA into release blogposts on the website for ORM...

**Comment by Ocramius** [comment]
@zeroedin-bill yeah, but that page shouldn't be for logged-in users only.

What about it, do you know more, @beberlei? Maybe @asgrim (since you deal with this jira stuff as well, sometimes)?

**Pull request merged**
