### PR TITLE
Fix clicking next link

### PR DESCRIPTION
**Pull request by harikt**
With @Ocramius comment on https://github.com/doctrine/doctrine-website-sphinx/pull/85 .

### CODE REVIEW

**Comment by harikt** [comment]
Thank you. @beberlei when will these changes get pushed to live ?

**Comment by harikt** [comment]
Hi @doctrine-team, 

When will this fix get deployed ? Or doesn't this fix the issue ?

**Comment by mikeSimonson** [comment]
@harikt It's already there. Did you refresh your cache ?

**Comment by harikt** [comment]
I did tried. I am looking inspecting it , see screenshot.

screenshot_2015-09-19_11-01-57

Is there any changes you see at your end ?

**Comment by mikeSimonson** [comment]
funny enough. It's fixed on the blog page (were I looked) but not on the main one.
Either a weird cache issue or that main.css is copy pasted somewhere.

**Comment by harikt** [comment]
:-) . to anyone looking this is the link http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/getting-started.html I am checking. And the css style is not yet fixed in that. Either I send a wrong fix or it is using some other css .

**Pull request merged**
